### PR TITLE
[RaghuMalayalam] readable name for glyphs

### PR DESCRIPTION
**Pull request by jishnu7**

### CODE REVIEW

**Comment by copyninja** [comment]
I can't see the diff! 667 additions and 667 deletion what did you do?

**Comment by jishnu7** [comment]
changed glyph names from unicode point number to easily readable strings, with same naming convention as meera and rachana.

**Comment by santhoshtr** [comment]
Typo in commit message - RaghyMalayalam -> RaghuMalayalam.

**Comment by copyninja** [comment]
@santhoshtr you can edit that message by rebasing it, for @jishnu7 it will not be straight forward task he need to ammend and force push the already public commit and then edit this PR.

**Comment by jishnu7** [comment]
I'll update.

**Comment by jishnu7** [comment]
@santhoshtr updated.

**Comment by santhoshtr** [comment]
ok, unless anybody else review this before , I will review during this weekend. thanks

**Comment by rajeeshknambiar** [comment]
I have reviewed, looks okay. I will do more review once they end up in
savannah repo.

On Tue, Jan 7, 2014 at 2:45 PM, Santhosh Thottingal <
notifications@github.com> wrote:

> ok, unless anybody else review this before , I will review during this
> weekend. thanks
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/smc/fonts/pull/4#issuecomment-31737907
> .

## 

Cheers,
Rajeesh
http://rajeeshknambiar.wordpress.com

**Pull request merged**
